### ISSUE TITLE
dtype problem

### ISSUE THREAD

**Issue by ahmetax** [robosoup/Word2Vec#1]
Hi,
When I run your Word2Vec codes I get  "ValueError: Tensor conversion requested dtype int32 for Tensor with dtype float32: 'Tensor("nce_loss/Reshape_1:0", shape=(?, 1, ?), dtype=float32)'" message.
It might be because of version mismatching of some libraries.
I am using:
Ubuntu 16.04 64 bit
Python 3.5.2
matplotlib 1.5.3
tensorflow 1.0.0
sklearn 0.0
numpy 1.12.0
Any confliction with your library versions?
Thank you.

**Comment by robosoup** [comment]
I developed the original code on an older version of TensorFlow. The order of the parameters of the function nce_loss() in TensorFlow 1.0 has changed. To correct the error, you just need to exchange the position of 'input_embeddings' and 'labels', or pull down the latest version of code which has now been updated for Tensorflow 1.0
